### ISSUE TITLE
Many hardcoded URLs

### ISSUE THREAD

**Issue by TrueBrain** [OpenTTD/website#25]
On several places we have URLs to places like binaries.openttd.org, proxy.binaries.openttd.org, READMEs, Changelogs, etc. This is a bit difficult to maintain, as there is not a single place to change it. You have to know where to look to change them.

We also have links to 'about.html', and we are not using Jekyll to tell us the URL of that page. This makes changing the URL schema very difficult.

It would be nice to reduce this way of referencing URLs. Please look into this and come up with a proper solution (if possible).

**Comment by claman** [comment]
so the goal would be to replace them with relative URLs where possible?

**Comment by TrueBrain** [comment]
Okay, the ticket was a bit vague. Fixed that now :)

And no, I was not suggesting to make things into relative URLs (in many places we even can't). But hopefully the new description is more clear :D But the ticket in other words: I rather have a single place/variable with a reference to an URL, than have it copied 10 times in all sorts of places.

**Comment by claman** [comment]
Aha, gotcha. That's definitely clearer now :)

It's looking the best way will be to use the `_data` folder: https://jekyllrb.com/docs/datafiles/, since that lets us define custom variables that will be accessible site-wide

This tutorial might also be useful: https://jekyllrb.com/tutorials/navigation/ (not sure, but it seems worth including).

I can take a bit more of a look when I have some free time this weekend.

**Comment by TrueBrain** [comment]
I am myself not even sure what this ticket was about. Clearly not a priority :) Closing it up!
