### ISSUE TITLE
footer/header of servers.openttd.org

### ISSUE THREAD

**Issue by planetmaker** [OpenTTD/website#63]
The server listing is missing header, menu and footer.
https://servers.openttd.org/en/

**Comment by auge8472** [comment]
I also saw that the server listing page misses the mentioned elements. As far I can see, the server listing is not really part of the sources.

**Comment by glx22** [comment]
It's still on the old infra IIRC

**Comment by TrueBrain** [comment]
Not sure you are seeing what I am seeing. It has a header. It has a footer.

![image](https://user-images.githubusercontent.com/1663690/53360532-0c5dc580-3936-11e9-82d0-5226291c44cf.png)
That does look like a header to me?

It does not have a menu, but that is on purpose. There is nothing to menu, basically :) I could add a single entry, like on http://security.openttd.org/en, but not sure that really makes a difference.

But yeah, this site still lives on the old infrastructure. As such, I am not really moved to change it. Unless there really is a bug, like really a missing header/footer. But I see the header/footer just fine, just like on any other subdomain of ours (like https://bananas.openttd.org/en). Am I missing something?

**Comment by TrueBrain** [comment]
Right, after talking on IRC, the issue really was lacking a description:

- because 'servers' is on a different subdomain, the header/menu changes. This is the only link in our www menu that points to a site similar looking, and as such it jumps out more. The fact that Community also lacks the menu is therefor less of an issue. Not sure what can be done about this.
- There is no menu on this page. We could add a single entry, like on security.
- The footer on all old-infrastructure (bananas, security, servers, ..) looks weird, because it has an empty box (used to be where we showed the banners). This could be removed completely.
- The logo points to a weird address. This is fixable.

**Comment by TrueBrain** [comment]
Fixed 3 out of the 4 issues mentioned above. The last one is not easy to fix; at least, I don't really have ideas. Also not sure it is worth any time, as that part of the website should be replaced anyway.

Going to close this for now. If you find more issues, please open a new bug (and please, be more descriptive :D). Tnx!

**Comment by auge8472** [comment]
A real™️ solution for the missed menu would be a *complete* menu and not only the single menu point that points to itself. I want to jump to differnet pages with the help of the menu and with no or the current single point menu I can't.

I expect the menu on the server listing page to be something like a handmade menu without an automatism for inclusion of new menu points. That's a drawback because someone has to remember the need of an adaption of the server listing menu.

I've no idea how to solve this problem but wanted to share my thoughts.
