### ISSUE TITLE
IPv6 access broken

### ISSUE THREAD

**Issue by michicc** [OpenTTD/website#90]
Accessing the website via IPv6 (either production or staging) result in a connection reset. IPv4 works.

`wget www.openttd.org`
`URL transformed to HTTPS due to an HSTS policy`
`--2019-06-09 11:21:28--  https://www.openttd.org/`
`Resolving www.openttd.org (www.openttd.org)... 2a03:b0c0:2:d0::dc6:7001, 178.128.140.43`
`Connecting to www.openttd.org (www.openttd.org)|2a03:b0c0:2:d0::dc6:7001|:443... connected.`
`GnuTLS: The TLS connection was non-properly terminated.`
`Unable to establish SSL connection.`

**Comment by TrueBrain** [comment]
Should be solved now. Please close the ticket if it is the case, otherwise let me know :)

As IPv6 is not natively supported by DigitalOcean, there is a proxy to handle IPv6. It needs internal IPs from the kubernetes cluster we run. These IPs change when ever an update is performed of the cluster. This happened ~20 hours ago. After that, it needs manual configuration change for IPv6 to kick in again. I will see if I can automate it :)

**Comment by michicc** [comment]
Working for me now.
